# Generated by Django 4.0.5 on 2022-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paperback',
            field=models.CharField(choices=[('Paperback', 'Paperback'), ('HardCover', 'HardCover')], default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
