# Generated by Django 4.0.5 on 2022-06-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_rating_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Web Framework', 'Web Framework'), ('Programming Language', 'Programming Languages'), ('CS Subjects', 'CS Subjects'), ('Databases', 'Databases'), ('Exams', 'Exams')], default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='paperback',
            field=models.CharField(choices=[('Paperback', 'Paperback'), ('HardCover', 'HardCover'), ('Audiobook', 'Audiobook')], max_length=100),
        ),
    ]
