# Generated by Django 4.0.5 on 2022-06-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_category_alter_product_paperback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
