# Generated by Django 4.0.5 on 2022-06-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pid',
            new_name='prid',
        ),
    ]
