# Generated by Django 4.0.5 on 2022-06-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_pid_product_prid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
