# Generated by Django 4.0.5 on 2022-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
