# Generated by Django 4.0.5 on 2022-06-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0006_intern_register_study_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobposting',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=2000)),
                ('location', models.CharField(max_length=100)),
                ('stipend', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.company_register')),
            ],
        ),
    ]
