# Generated by Django 4.0.5 on 2022-06-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Marketing', 'Marketing'), ('Testing', 'Testing'), ('Sales & Support', 'Sales & Support')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
