# Generated by Django 4.0.5 on 2022-06-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_jobposting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='duration',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
