# Generated by Django 4.0.5 on 2022-06-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_jobposting_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='duration',
            field=models.CharField(choices=[('Part-time', 'part-time'), ('Full-time', 'full-time')], max_length=100),
        ),
    ]
