# Generated by Django 4.0.5 on 2022-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_alter_jobposting_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
