# Generated by Django 4.0.5 on 2022-06-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_alter_jobposting_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='post',
            new_name='posttitle',
        ),
    ]
