# Generated by Django 4.0.5 on 2022-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_register',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_username', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('conpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='intern_register',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('iemail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('dob', models.DateField()),
                ('degree', models.CharField(choices=[('bachelor', 'bachelor'), ('Master', 'Masters'), ('P.HD', 'P.HD'), ('HSC', 'HSC')], max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('colleg_city', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
    ]
