# Generated by Django 4.0.5 on 2022-06-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_conpassword_company_register_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern_register',
            name='phone',
        ),
    ]
