# Generated by Django 4.0.5 on 2022-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_intern_register_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_register',
            name='study_field',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
