# Generated by Django 4.0.5 on 2022-06-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_intern_register_study_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_register',
            name='desc',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_register',
            name='sector',
            field=models.CharField(choices=[('I.T', 'I.T'), ('Healthcare', 'HealthCare'), ('Real Estate', 'Real Estate'), ('Ecommerce', 'Ecommerce'), ('Food', 'Food'), ('Space', 'Space'), ('Automobile', 'Automobile'), ('logistics', 'logistics')], default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_register',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
