# Generated by Django 4.0.5 on 2022-06-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_company_register_desc_company_register_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_register',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company_register',
            name='sector',
            field=models.CharField(choices=[('I.T', 'I.T'), ('Healthcare', 'HealthCare'), ('Real Estate', 'Real Estate'), ('Ecommerce', 'Ecommerce'), ('Food', 'Food'), ('Space', 'Space'), ('Fintech', 'Fintech'), ('Automobile', 'Automobile'), ('logistics', 'logistics')], max_length=100),
        ),
    ]
