# Generated by Django 4.0.5 on 2022-06-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
